export const TOKEN_PLAYED = 'TOKEN_PLAYED';
export const RESET_GAME = 'RESET_GAME';
export const PLAYER_NAME_CHANGED = 'PLAYER_NAME_CHANGED';
export const RESET_SCORES = 'RESET_SCORES';

export const GAME_RESULT_SAVE_SENT = 'GAME_RESULT_SAVE_SENT';
export const GAME_RESULT_SAVE_SUCCEEDED = 'GAME_RESULT_SAVE_SUCCEEDED';
export const GAME_RESULT_SAVE_FAILED = 'GAME_RESULT_SAVE_FAILED';